[package]
name = "feos-gc-pcsaft"
version = "0.1.0"
authors = ["Philipp Rehner <prehner@ethz.ch>", "Gernot Bauer <bauer@itt.uni-stuttgart.de>"]
edition = "2018"

[lib]
name = "feos_gc_pcsaft"
crate-type = ["rlib", "cdylib"]

[dependencies]
quantity = "0.3"
feos-core = { git = "https://github.com/feos-org/feos-core", branch = "main" }
feos-dft = { git = "https://github.com/feos-org/feos-dft", branch = "main" }
num-dual = "0.3"
num = "*"
ndarray-linalg = "0.14"
ndarray = { version = "0.15", features=["approx"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
indexmap = "1.3.2"
lazy_static = "1.4.0"
thiserror = "1.0"
numpy = { version = "0.14", optional = true }

[dev-dependencies]
approx = "0.4"

[dependencies.pyo3]
version = "0.14"
features = ["extension-module", "abi3", "abi3-py36"]
optional = true

[features]
default = []
python = ["pyo3", "numpy", "feos-dft/python"]
openblas-system = ["feos-core/openblas-system"]
openblas-static = ["feos-core/openblas-static"]
intel-mkl-system = ["feos-core/intel-mkl-system"]
intel-mkl-static = ["feos-core/intel-mkl-static"]
netlib-system = ["feos-core/netlib-system"]
netlib-static = ["feos-core/netlib-static"]
